"""Release-bound retrieval, fixed multi-view Probe, and intent transparency."""

from .bundle import (
    decode_dense_index_manifest,
    encode_dense_index_manifest,
    load_dense_index,
    validate_dense_index,
    write_dense_index,
)
from .calibration import (
    BoundTransparencyCalibration,
    TransparencyCalibrationConfigError,
    load_bound_transparency_calibration,
)
from .coherence import ProbeCoherence, compute_catalog_mean, compute_probe_coherence
from .compiled_probe import CompiledDenseProbeRun, CompiledDenseProbeRunner
from .controller import (
    FormalRetrievalHit,
    FormalRetrievalPolicy,
    FormalRetrievalResult,
    RetrievalController,
)
from .dense import (
    DenseEligibilityMask,
    DenseIndex,
    DenseRetriever,
    DenseScoreSnapshot,
    DenseSearchResult,
)
from .documents import ProductDocument, ProductDocumentError, load_product_documents
from .embedding import SentenceTransformerTextEmbedder, TextEmbedder
from .errors import (
    CompiledQueryBindingError,
    CompiledQueryNotSearchableError,
    DenseIndexBusyError,
    DenseIndexIntegrityError,
    EmbeddingBackendUnavailableError,
    QueryEmbeddingError,
    RankingBackendUnavailableError,
    RetrievalError,
)
from .evidence import (
    RETRIEVAL_EVIDENCE_POLICY_ID,
    RETRIEVAL_EVIDENCE_SCHEMA,
    SUPPORTED_FACETS,
    RetrievalEvidenceError,
    RetrievalEvidenceIndex,
    build_retrieval_evidence_index,
)
from .factory import (
    create_compiled_probe_runner,
    create_dense_retriever,
    create_resolved_compiled_probe_runner,
    create_retrieval_controller,
)
from .fusion import (
    FusedCandidate,
    ReciprocalRankFusion,
    RelativeScoreFusion,
    RouteContribution,
    normalized_fusion_relevance,
)
from .hard_mask import (
    ConstraintDisposition,
    ConstraintResolutionTrace,
    HardMaskResolutionError,
    HardMaskResolver,
    ResolvedHardMask,
)
from .intent_volume import (
    INTENT_TRANSPARENCY_SCHEMA,
    INTENT_VOLUME_MAPPING_ID,
    INTENT_VOLUME_POLICY_ID,
    CatalogDensitySnapshot,
    IntentTransparencyEstimate,
    IntentVolumeDiagnostics,
    IntentVolumeDirection,
    IntentVolumeEstimator,
    IntentVolumePolicy,
    IntentVolumeStatus,
    load_catalog_density,
    project_intent_transparency,
)
from .lexical import LexicalHit, LexicalProbe, LexicalProbeObservation
from .models import DenseHit, DenseIndexManifest, EmbeddingSpec, default_embedding_spec
from .modes import (
    SemanticMode,
    SemanticModeMembership,
    SemanticModeObservation,
    SemanticModeProbe,
)
from .multi_probe import CompiledProbeRun, CompiledProbeRunner, ProbeSnapshot
from .probe import DenseProbeObservation, FixedDenseProbe
from .ranking import (
    CrossEncoderRankingHit,
    CrossEncoderRankingResult,
    CrossEncoderRelevanceReranker,
    CrossEncoderScorer,
    GreedyDPPSelector,
    LatentAspectXQuADSelector,
    SentenceTransformerCrossEncoderScorer,
    VectorSlateHit,
    VectorSlateResult,
)
from .resolved_probe import ResolvedCompiledProbeRun, ResolvedCompiledProbeRunner
from .routing import (
    FacetRoute,
    RetrievalRoute,
    RouteHit,
    RouteObservation,
    dense_route_observation,
    lexical_route_observation,
)
from .transparency import (
    DiagnosticStatus,
    ProbeDiagnostics,
    TransparencyCalibration,
    TransparencyEstimate,
    TransparencyEstimator,
    TransparencyEvidence,
    estimate_transparency,
    project_search_belief,
)
from .vector_diversity import (
    CandidateVectorDiversityHit,
    CandidateVectorDiversityResult,
    VectorCandidate,
    VectorDiversityHit,
    VectorDiversityPolicy,
    VectorDiversityResult,
    VectorMMRReranker,
)

__all__ = [
    "BoundTransparencyCalibration",
    "CompiledDenseProbeRun",
    "CompiledDenseProbeRunner",
    "CompiledProbeRun",
    "CompiledProbeRunner",
    "CompiledQueryBindingError",
    "CompiledQueryNotSearchableError",
    "DenseEligibilityMask",
    "DenseHit",
    "DenseIndex",
    "DenseIndexBusyError",
    "DenseIndexIntegrityError",
    "DenseIndexManifest",
    "DenseProbeObservation",
    "DenseRetriever",
    "DenseScoreSnapshot",
    "DenseSearchResult",
    "EmbeddingBackendUnavailableError",
    "EmbeddingSpec",
    "FacetRoute",
    "FormalRetrievalHit",
    "FormalRetrievalPolicy",
    "FormalRetrievalResult",
    "FusedCandidate",
    "ConstraintDisposition",
    "ConstraintResolutionTrace",
    "FixedDenseProbe",
    "HardMaskResolutionError",
    "HardMaskResolver",
    "INTENT_TRANSPARENCY_SCHEMA",
    "INTENT_VOLUME_MAPPING_ID",
    "INTENT_VOLUME_POLICY_ID",
    "CatalogDensitySnapshot",
    "IntentTransparencyEstimate",
    "IntentVolumeDiagnostics",
    "IntentVolumeDirection",
    "IntentVolumeEstimator",
    "IntentVolumePolicy",
    "IntentVolumeStatus",
    "LexicalHit",
    "LexicalProbe",
    "LexicalProbeObservation",
    "ProbeCoherence",
    "ProbeDiagnostics",
    "ProbeSnapshot",
    "ProductDocument",
    "ProductDocumentError",
    "QueryEmbeddingError",
    "RankingBackendUnavailableError",
    "RETRIEVAL_EVIDENCE_POLICY_ID",
    "RETRIEVAL_EVIDENCE_SCHEMA",
    "ResolvedCompiledProbeRun",
    "ResolvedCompiledProbeRunner",
    "ResolvedHardMask",
    "RetrievalEvidenceError",
    "RetrievalEvidenceIndex",
    "RetrievalError",
    "RetrievalController",
    "RetrievalRoute",
    "ReciprocalRankFusion",
    "RelativeScoreFusion",
    "RouteContribution",
    "RouteHit",
    "RouteObservation",
    "SentenceTransformerTextEmbedder",
    "SemanticMode",
    "SemanticModeMembership",
    "SemanticModeObservation",
    "SemanticModeProbe",
    "TextEmbedder",
    "TransparencyCalibration",
    "TransparencyCalibrationConfigError",
    "TransparencyEstimate",
    "TransparencyEstimator",
    "TransparencyEvidence",
    "DiagnosticStatus",
    "SUPPORTED_FACETS",
    "build_retrieval_evidence_index",
    "compute_catalog_mean",
    "compute_probe_coherence",
    "create_compiled_probe_runner",
    "create_dense_retriever",
    "create_retrieval_controller",
    "create_resolved_compiled_probe_runner",
    "decode_dense_index_manifest",
    "default_embedding_spec",
    "encode_dense_index_manifest",
    "estimate_transparency",
    "dense_route_observation",
    "load_dense_index",
    "load_catalog_density",
    "load_bound_transparency_calibration",
    "load_product_documents",
    "project_search_belief",
    "project_intent_transparency",
    "lexical_route_observation",
    "normalized_fusion_relevance",
    "validate_dense_index",
    "CandidateVectorDiversityHit",
    "CandidateVectorDiversityResult",
    "VectorCandidate",
    "VectorDiversityHit",
    "VectorDiversityPolicy",
    "VectorDiversityResult",
    "VectorMMRReranker",
    "CrossEncoderRankingHit",
    "CrossEncoderRankingResult",
    "CrossEncoderRelevanceReranker",
    "CrossEncoderScorer",
    "GreedyDPPSelector",
    "LatentAspectXQuADSelector",
    "SentenceTransformerCrossEncoderScorer",
    "VectorSlateHit",
    "VectorSlateResult",
    "write_dense_index",
]
