"""Public CS1 category contract, builders, validators, codecs, and bundle API."""

from .build import (
    build_category_candidate,
    build_category_graph_proposal,
    category_scope_selection_template,
    reviewed_category_scopes_candidate_document,
)
from .bundle import (
    validate_category_bundle,
    write_category_candidate_bundle,
    write_category_graph_proposal_bundle,
)
from .codec import (
    decode_category_registry,
    decode_product_category_assignment_set,
    decode_scope_selection,
    encode_category_registry,
    encode_product_category_assignment_set,
)
from .models import (
    CATEGORY_REGISTRY_SCHEMA,
    CATEGORY_SCOPE_SELECTION_SCHEMA,
    PRODUCT_CATEGORY_ASSIGNMENT_SCHEMA,
    CategoryCandidateBuild,
    CategoryGraphProposal,
    CategoryMatchResult,
    CategoryNode,
    CategoryNormalizationCollision,
    CategoryRegistry,
    CategoryScope,
    CategoryScopeSelection,
    CategoryScopeSelectionDocument,
    ProductCategoryAssignment,
    ProductCategoryAssignmentSet,
    ProductCategoryAssignmentStatus,
    RawPathMapping,
)
from .normalization import (
    CATEGORY_BUILDER_VERSION,
    CATEGORY_NORMALIZER_ID,
    CATEGORY_UNICODE_DATA_VERSION,
    category_node_id,
    normalize_category_path,
    normalize_category_segment,
)
from .validation import (
    category_graph_core_document,
    category_graph_id,
    category_scope_id,
    match_category,
    materialize_category_scope,
    validate_category_nodes,
    validate_category_registry,
    validate_category_scope,
    validate_official_p0_assignments,
    validate_product_category_assignment_set,
)

__all__ = [
    "CATEGORY_BUILDER_VERSION",
    "CATEGORY_NORMALIZER_ID",
    "CATEGORY_REGISTRY_SCHEMA",
    "CATEGORY_SCOPE_SELECTION_SCHEMA",
    "CATEGORY_UNICODE_DATA_VERSION",
    "PRODUCT_CATEGORY_ASSIGNMENT_SCHEMA",
    "CategoryCandidateBuild",
    "CategoryGraphProposal",
    "CategoryMatchResult",
    "CategoryNode",
    "CategoryNormalizationCollision",
    "CategoryRegistry",
    "CategoryScope",
    "CategoryScopeSelection",
    "CategoryScopeSelectionDocument",
    "ProductCategoryAssignment",
    "ProductCategoryAssignmentSet",
    "ProductCategoryAssignmentStatus",
    "RawPathMapping",
    "build_category_candidate",
    "build_category_graph_proposal",
    "category_graph_core_document",
    "category_graph_id",
    "category_node_id",
    "category_scope_id",
    "category_scope_selection_template",
    "decode_category_registry",
    "decode_product_category_assignment_set",
    "decode_scope_selection",
    "encode_category_registry",
    "encode_product_category_assignment_set",
    "match_category",
    "materialize_category_scope",
    "normalize_category_path",
    "normalize_category_segment",
    "reviewed_category_scopes_candidate_document",
    "validate_category_bundle",
    "validate_category_nodes",
    "validate_category_registry",
    "validate_category_scope",
    "validate_official_p0_assignments",
    "validate_product_category_assignment_set",
    "write_category_candidate_bundle",
    "write_category_graph_proposal_bundle",
]
