"""Public API for deterministic, read-only raw catalog profiling."""

from .bundle import (
    PROFILE_ARTIFACT_FILENAMES,
    PROFILE_BUNDLE_FILENAMES,
    PROFILE_BUNDLE_MANIFEST_FILENAME,
    ProfileBundleBusyError,
    ProfileBundleIntegrityError,
    validate_profile_bundle,
    write_profile_bundle,
)
from .models import (
    CatalogProfile,
    CategoryDetailCoverage,
    CategoryNode,
    DetailKeyProfile,
    DiagnosticProfile,
    DiagnosticSample,
    ProductCategoryAssignment,
    ProfileConfig,
    TopLevelFieldProfile,
    TypeCount,
    ValueMass,
    ValueSample,
)
from .profiler import (
    AssignmentSink,
    CatalogChangedError,
    canonical_json_dumps,
    catalog_file_sha256,
    category_id_for_path,
    profile_catalog,
)
from .reporting import (
    CanonicalAssignmentJsonlSink,
    catalog_profile_to_json,
    catalog_profile_to_markdown,
    product_category_assignment_to_json,
    write_catalog_profile_json,
    write_category_detail_coverage_jsonl,
    write_category_nodes_jsonl,
    write_detail_keys_jsonl,
)

__all__ = (
    "AssignmentSink",
    "CanonicalAssignmentJsonlSink",
    "CatalogChangedError",
    "CatalogProfile",
    "CategoryDetailCoverage",
    "CategoryNode",
    "DetailKeyProfile",
    "DiagnosticProfile",
    "DiagnosticSample",
    "ProductCategoryAssignment",
    "PROFILE_ARTIFACT_FILENAMES",
    "PROFILE_BUNDLE_FILENAMES",
    "PROFILE_BUNDLE_MANIFEST_FILENAME",
    "ProfileBundleBusyError",
    "ProfileBundleIntegrityError",
    "ProfileConfig",
    "TopLevelFieldProfile",
    "TypeCount",
    "ValueMass",
    "ValueSample",
    "canonical_json_dumps",
    "catalog_file_sha256",
    "catalog_profile_to_json",
    "catalog_profile_to_markdown",
    "category_id_for_path",
    "product_category_assignment_to_json",
    "profile_catalog",
    "write_catalog_profile_json",
    "write_category_detail_coverage_jsonl",
    "write_category_nodes_jsonl",
    "write_detail_keys_jsonl",
    "write_profile_bundle",
    "validate_profile_bundle",
)
