"""Public provider-independent Query Understanding boundary."""

from .errors import QueryUnderstandingError, QueryUnderstandingErrorCode
from .models import (
    ActivePreferenceView,
    BehavioralDirectives,
    CategoryOption,
    ClarificationNeed,
    DiversityMode,
    FeedbackFrame,
    GoalAction,
    GoalFrame,
    MaterializationResult,
    NewPreferenceFrame,
    PreferenceBasis,
    PreferenceFrame,
    PreferenceRelation,
    PreferenceStrength,
    PricePreferenceFrame,
    ProviderResult,
    ProviderTrace,
    ReconciledIntentFrame,
    ReconcileRequest,
    ResolvedTurnIntent,
    SemanticPreferenceFrame,
    ShownProductView,
    StructuredPreferenceFrame,
    UnderstandingDisposition,
    UnderstandingTrace,
)
from .planner import IntentMaterializer
from .prompt import PROMPT_VERSION, SYSTEM_PROMPT, build_messages
from .service import QueryUnderstandingService, UnderstandingProvider
from .views import (
    build_reconcile_request,
    category_options_from_registry,
    request_payload,
)
from .wire import TOOL_NAME, decode_reconciled_intent, reconcile_session_intent_tool

__all__ = (
    "PROMPT_VERSION",
    "SYSTEM_PROMPT",
    "TOOL_NAME",
    "ActivePreferenceView",
    "BehavioralDirectives",
    "CategoryOption",
    "ClarificationNeed",
    "DiversityMode",
    "FeedbackFrame",
    "GoalAction",
    "GoalFrame",
    "IntentMaterializer",
    "MaterializationResult",
    "NewPreferenceFrame",
    "PreferenceFrame",
    "PreferenceBasis",
    "PreferenceRelation",
    "PreferenceStrength",
    "PricePreferenceFrame",
    "ProviderResult",
    "ProviderTrace",
    "QueryUnderstandingError",
    "QueryUnderstandingErrorCode",
    "QueryUnderstandingService",
    "ReconcileRequest",
    "ReconciledIntentFrame",
    "ResolvedTurnIntent",
    "SemanticPreferenceFrame",
    "ShownProductView",
    "StructuredPreferenceFrame",
    "UnderstandingDisposition",
    "UnderstandingProvider",
    "UnderstandingTrace",
    "build_messages",
    "build_reconcile_request",
    "category_options_from_registry",
    "decode_reconciled_intent",
    "reconcile_session_intent_tool",
    "request_payload",
)
