"""Public boundary for immutable session-context state and transitions."""

from .aggregates import (
    InteractionContext,
    ProductFeedback,
    SessionContext,
    SessionState,
    TurnRecord,
)
from .errors import ErrorCode, SessionContextError
from .models import (
    CandidateMode,
    CertaintyEvidence,
    Commitment,
    FacetStats,
    FeedbackSignal,
    IntentState,
    Operator,
    Preference,
    PreferenceDraft,
    PreferenceSource,
    ProbeQuality,
    ProfilePrior,
    SearchBelief,
    SemanticPolarity,
    ValueMass,
)
from .operations import (
    AddPreference,
    ClearFacet,
    RemovePreference,
    ReplaceFacet,
    SetDontCare,
    StateUpdateBatch,
    SwitchGoal,
)
from .registry import (
    CATEGORICAL_OPERATORS,
    NUMERIC_OPERATORS,
    FacetKind,
    FacetRegistry,
    FacetSpec,
    canonical_number,
    canonical_text,
)
from .validation import (
    validate_intent_state,
    validate_preference,
    validate_profile_prior,
    validate_state_update_batch,
)

__all__ = (
    "CATEGORICAL_OPERATORS",
    "NUMERIC_OPERATORS",
    "AddPreference",
    "CandidateMode",
    "CertaintyEvidence",
    "ClearFacet",
    "Commitment",
    "ErrorCode",
    "FacetKind",
    "FacetRegistry",
    "FacetSpec",
    "FacetStats",
    "FeedbackSignal",
    "IntentState",
    "InteractionContext",
    "Operator",
    "Preference",
    "PreferenceDraft",
    "PreferenceSource",
    "ProbeQuality",
    "ProductFeedback",
    "ProfilePrior",
    "RemovePreference",
    "ReplaceFacet",
    "SearchBelief",
    "SemanticPolarity",
    "SessionContext",
    "SessionContextError",
    "SessionState",
    "SetDontCare",
    "StateUpdateBatch",
    "SwitchGoal",
    "TurnRecord",
    "ValueMass",
    "canonical_number",
    "canonical_text",
    "validate_intent_state",
    "validate_preference",
    "validate_profile_prior",
    "validate_state_update_batch",
)
